version: '3'
services:
    db:
        image: mysql:5.7
        restart: always
        command: mysqld
        environment:
            # MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: prisma
        ports:
            - '3306:3306'
